version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - '6379:6379'

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - '80:80'
    volumes:
      - ./nginx/html:/usr/share/nginx/html

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
